### ISSUE TITLE
Vulnerability in iPaaS hackathon code.

### ISSUE THREAD

**Issue by eschabell** [redhatdemocentral/rhsummitlabs-2018#32]
![screen shot 2018-05-02 at 15 05 54](https://user-images.githubusercontent.com/437001/39551564-5b0cf208-4e1a-11e8-8dd8-268f21041af4.png)

There's a vulnerability to be fixed in your deps.... see screenshot.

**Comment by weimeilin79** [comment]
Fix in pull #33 
https://github.com/redhatdemocentral/rhsummitlabs-2018/pull/33
